theme: jekyll-theme-merlot

# ignore_theme_config: true

# Site settings
title: Myndex on GitHub
author: Myndex Research
  name: Andrew Somers
  email: perception@myndex.com
description: "Myndex Research and Development — Creators of APCA"

